const MAX_COUNT_OF_ENEMIES_AT_MOMENT = 10;

const GENERATE_ENEMIES_INTERVAL_TIME = 350;

const DEADLINE = 10;

const RANGE_X = 10;

const RANGE_Y = 2;

const ENEMY_SIZE = 3;

const BACKGROUND_COLOR = "#feffde";
